# Generated by Django 5.0.6 on 2024-06-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_type', models.CharField(choices=[('postgreSQL', 'PostgreSQL'), ('Oracle', 'Oracle')], max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('copy', models.BooleanField(default=False)),
            ],
        ),
    ]
